version: "2"
services:
    mongodb:
        container_name: mongo_prod
        image: mongo
        ports:
         - "27018:27017"

    app:
        build:
            context: .
            args:
                - ENV=prod
        container_name: devops_app
        ports:
            - "3000:3000"
        environment:
            - MONGODB_URL=mongodb://mongo_prod:27017/todo-app
            - ENV=prod
        tty: true
